# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-16 01:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=16)),
                ('imagesource', models.TextField()),
                ('fractype', models.CharField(max_length=16)),
                ('rowres', models.IntegerField(default=0)),
                ('colres', models.IntegerField(default=0)),
                ('xmin', models.FloatField(default=0)),
                ('xmax', models.FloatField(default=0)),
                ('ymin', models.FloatField(default=0)),
                ('ymax', models.FloatField(default=0)),
                ('cr', models.FloatField(default=0)),
                ('ci', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=16)),
                ('password', models.CharField(max_length=16)),
            ],
        ),
    ]
